import Head from "next/head";
import Image from "next/image";
import React from "react";
import HeaderLink from "../components/HeaderLink";
import {getProviders,signIn} from 'next-auth/react'
import {
  Explore,
  Group,
  OndemandVideo,
  BusinessCenter,
  ArrowForwardIosRounded,
} from "@material-ui/icons";
const home = ({providers}) => {
  
  return (
    <div className='space-y-10  relative'>
      <Head>
        <title>LinkedIn</title>
        <meta name='description' content='Generated by create next app' />
        <link
          rel='icon'
          href='https://img.freepik.com/free-psd/linkedin-apps-logo-round-square-3d-style-design-icon-asset-isolated_384205-87.jpg?size=338&ext=jpg'
        />
      </Head>
      <header className='flex items-center justify-around py-4'>
        <div className='relative w-36 h-10'>
          <Image src='https://rb.gy/vtbzlp' layout='fill' objectFit='contain' />
        </div>
        <div className='flex items-center sm:divide-x divide-gray-300 pl-2'>
          <div className='hidden sm:flex  pr-4 space-x-4'>
            <HeaderLink Icon={Explore} text='Discover' />
            <HeaderLink Icon={Group} text='People' />
            <HeaderLink Icon={OndemandVideo} text='Learning' />
            <HeaderLink Icon={BusinessCenter} text='Jobs' />
          </div>
          {Object.values(providers).map((provider) => (
            <div key={provider.name}>
              <div className='pl-4'>
                <button
                  className='text-blue-700 font-semibold rounded-full border border-blue-700 px-5 py-1.5 transition-all  hover:border-2'
                  onClick={() => signIn(provider.id, { callbackUrl: "/" })}
                >
                  Sign In with {provider.name}
                </button>
              </div>
            </div>
          ))}
        </div>
      </header>
      <main className='flex flex-col xl:flex-row items-center max-w-screen-xl mx-auto'>
        <div className='space-y-6 xl:space-y-10'>
          <h1 className='text-3xl md:text-5xl text-amber-800/80 max-w-xl  !leading-snug  xl:pl-0'>
            Welcome to your Proffessional community{" "}
          </h1>
          <div className='space-y-4'>
            <div className='intent'>
              <h2 className='text-2xl'>Search For a job</h2>
              <ArrowForwardIosRounded className='text-gray-700' />
            </div>
            <div className='intent'>
              <h2 className='text-2xl'>Find a person You know</h2>
              <ArrowForwardIosRounded className='text-gray-700' />
            </div>
            <div className='intent'>
              <h2 className='text-2xl'>Learn a skill</h2>
              <ArrowForwardIosRounded className='text-gray-700' />
            </div>
          </div>
        </div>
        <div className='relative  h-80 w-80 xl:w-[650px] xl:h-[650px] xl:absolute right-5 top-14 '>
          <Image src='https://rb.gy/vkzpzt' layout='fill' priority />
        </div>
      </main>
    </div>
  );
};
// 
export async function getServerSideProps(context) {
  const providers = await getProviders();

  return {
    props: {
      providers,
    },
  };
}
export default home;

